### ISSUE TITLE
Gracefully handle StackExchange API errors

### ISSUE THREAD

**Issue by ryancwalsh** [ryancwalsh/StackExchangeBackupLaravelPHP#11]
There are 2 cases I know about and want to handle:
1. Sometimes Guzzle fetches an empty response. In these cases, I'd want to retry once or twice, and if it still fails, I'd want to add a message to an array of errors that gets displayed in a console at the end. This way, one endpoint failing doesn't stop the _whole_ backup process. Then, ideally, I'd also offer a way for a user to re-run a subset of their SE sites (so that they could choose to run just the ones that failed).
1. Sometimes SE might return a `503 Service Unavailable` response ("Too Many Requests").

```
[2019-09-13 03:47:18] local.ERROR: ryancwalsh\StackExchangeBackupLaravel\ExportStackExchangeCommand handle GuzzleHttp\Exception\ServerException: Server error: `GET https://api.stackexchange.com/2.2/me/favorites?site=quant.stackexchange.com&pagesize=100&page=1&sort=creation&order=desc&filter=withbody&code=ArLz29%29&access_token=WFV%29&key=JuWsT` resulted in a `503 Service Unavailable` response:
<html> 
  <head>
    <title>Too Many Requests - Stack Exchange</title>
  </head> 
  <body style="font-family:Arial,Helve (truncated...)
 in /home/vagrant/Code/backupSaver/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/vagrant/Code/backupSaver/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /home/vagrant/Code/backupSaver/packages/ryancwalsh/stack-exchange-backup-laravel/src/ExportStackExchangeHelper.php(116): GuzzleHttp\Client->request('get', 'https://api.sta...')
#11 /home/vagrant/Code/backupSaver/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(383): ryancwalsh\StackExchangeBackupLaravel\ExportStackExchangeHelper->ryancwalsh\StackExchangeBackupLaravel\{closure}()
#12 /home/vagrant/Code/backupSaver/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(357): Illuminate\Cache\Repository->remember('5dd3bf44af75540...', 60, Object(Closure))
#13 /home/vagrant/Code/backupSaver/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Illuminate\Cache\CacheManager->__call('remember', Array)
#14 /home/vagrant/Code/backupSaver/packages/ryancwalsh/stack-exchange-backup-laravel/src/ExportStackExchangeHelper.php(118): Illuminate\Support\Facades\Facade::__callStatic('rem
```

**Comment by ryancwalsh** [comment]
Hmm. Even when `quota_remaining=9281 `, I just got this error `503 Service Unavailable`  "Too Many Requests - Stack Exchange".

Related question: https://stackapps.com/questions/6393/how-to-deal-with-the-too-many-requests-error-coming-as-html

**Comment by ryancwalsh** [comment]
I tried using https://github.com/spatie/guzzle-rate-limiter-middleware but noticed no impact, and then I realized that `sleep` does not work in WSL: https://stackoverflow.com/questions/62930112/why-doesnt-php-sleep-work-in-the-windows-subsystem-linux

**Comment by ryancwalsh** [comment]
Even using Homestead Vagrant instead of WSL, I couldn't seem to get RateLimiterMiddleware working.

But I temporarily locally set these values in ExportStackExchangeHelper, and I was able to complete the whole backup:

```
const PAUSE_BETWEEN_REQUESTS_MS = 2000;
const REQUESTS_PER_MIN = 30;
```

**Comment by ryancwalsh** [comment]
https://stackapps.com/a/1469/55248:

> API throttling has been fixed.
> 
> "30 reqs per 5 seconds" is now strictly true again, rather than just true for common use cases.
> 
> Kevin Montrose♦
> 2010-08-24

That is 6 requests per second, which is 360 per minute, but I don't know if that is accurate today.

Also, I don't understand my previous comment, if WSL can't support sleep. I still got this error `503 Service Unavailable` "Too Many Requests - Stack Exchange" today on WSL even with those values for the constants.

Ahh, but it did work on Homestead; I guess Vagrant supports `usleep`.

It even worked sped up a tad:

    const PAUSE_BETWEEN_REQUESTS_MS = 400;
    const REQUESTS_PER_MIN = 60;

**Comment by ryancwalsh** [comment]
I made a bunch of commits to this repo to upgrade the Laravel dependency, etc. Then I followed the instructions in the readme.

Then I ran the command in WSL 1, and everything worked on the first try! 100% of the downloads completed and uploaded backups to S3. It took just less than 5 mins according to the timestamps.
